# #This is mongo config file #ConfigMap

# #THIS FILE WILL HAVE ENDPOINT OF MONGO DB AND ITS INFO
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: mongo-config
#   # namespace: database-tier
# data:
#   mongo-url: mongo-service #service name 
