#Pod for FE CODE
#AKMS

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend-tier
  # labels:
  #   env: dev
  #   app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-frontend-deployment #POD WILL BE LABELED WITH THIS
  template:
    metadata:
      labels:
        app: my-frontend-deployment #POD WILL BE LABELED WITH THIS
    spec:
      containers:
        - name: frontend-container-deployment-pod
          image: captianvigg06/devops-project:frontend-image-v1.0.0
          #imagePullPolicy: IfNotPresent #Only pull the image if it is not present locally
          imagePullPolicy: Always #Always pull the image from the registry
          ports:
            - containerPort: 3000
