#AKSM
#CHANGES TO SEE LINK BETWEEN WORKFLOW AND MANIFEST FILES AND ARGOCD

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  # namespace: backend-database-tier
  labels:
    app: my-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-backend-deployment
  template:
    metadata:
      labels:
        app: my-backend-deployment
    spec:
      containers:
        - name: backend-container-deployment-pod
          image: captianvigg06/devops-project:backend-image-v1.0.0
          imagePullPolicy: Always #Always pull the image from the registry
          ports:
            - containerPort: 3500
          env:
            - name: MONGO_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_CONN_STR
                  
          # - name: MONGO_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongo-secret
          #       key: mongo-user

          # - name: MONGO_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongo-secret
          #       key: mongo-password

          # - name: MONGO_HOST
          #   value: mongo-service

          # - name: MONGO_PORT
          #   value: "27017"

          # - name: MONGO_DB
          #   value: backenddb